### ISSUE TITLE
Zurb Foundation 6 into Bootstrap 4

### ISSUE THREAD

**Issue by Ttanus** [Ttanus/Tirtayasa#2]
Mengganti penggunaan Zurb Foundation ke Bootstrap.

**Comment by williamo1099** [comment]
Sudah mencoba menghapus penggunaan Foundation (mayoritas CSS) dengan penggunaan Bootstrap 4.4.1

**Comment by williamo1099** [comment]
Sedang mencoba mengubah routing result dengan menggunakan Bootstrap, namun masih ada masalah perubahan panel

**Comment by williamo1099** [comment]
Convert ke bootstrap sudah selesai.
